### ISSUE TITLE
Electron TODO

### ISSUE THREAD

**Issue by ajusa** [Ajusa/Scouting2016Server#2]
Functionality List:
- [ ] ASK JON
- [ ] Start Server
- [ ] Stop Server
- [ ] Save Server
- [ ] View Connected Scouts
- [ ] View Table of Data
- [ ] Change Competition Name?
